{{- define "secret.login" }}
{{- template "chart.fullname" . }}-mysql-service;3306;root;{{- template "getPassword" . -}};realmd
{{- end }}

{{- define "secret.world" -}}
{{- template "chart.fullname" . }}-mysql-service;3306;root;{{- template "getPassword" . -}};mangos{{- template "databaseSuffix" . -}}
{{- end }}

{{- define "secret.character" -}}
{{- template "chart.fullname" . }}-mysql-service;3306;root;{{- template "getPassword" . -}};character{{- template "databaseSuffix" . -}}
{{- end }}

{{- define "databaseSuffix" -}}
{{- /* versions < 2 and > 3 are suffixed with the version number */ -}}
{{- if or (lt (.Values.wowVersion | int) 2) (gt (.Values.wowVersion | int) 3) -}}
{{- .Values.wowVersion -}}
{{- end -}}
{{- end -}}

{{- define "getPassword" }}
{{- .Values.mysql.rootPassword | default (randAlphaNum 24) -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
    name: mangos-secret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: {{ include "getPassword" . | b64enc }}
    LOGIN_DATABASE_INFO: {{ include "secret.login" . | b64enc }}
    WORLD_DATABASE_INFO: {{ include "secret.world" . | b64enc }}
    CHARACTER_DATABASE_INFO: {{ include "secret.character" . | b64enc }}