{{- define "secret.login" }}
    {{ template "chart.fullname" . }}-mysql-service;3306;root;{{ template "getPassword" . }};realmd
{{- end }}

{{- define "secret.world" }}
    {{ template "chart.fullname" . }}-mysql-service;3306;root;{{ template "getPassword" . }};mangos0
{{- end }}

{{- define "secret.character" }}
    {{ template "chart.fullname" . }}-mysql-service;3306;root;{{ template "getPassword" . }};character0
{{- end }}

{{- define "getPassword" }}
    {{ .Values.mysql.rootPassword | default (randAlphaNum 24) }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
    name: mangoszero-secret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: {{ template "getPassword" . | b64enc }}
    LOGIN_DATABASE_INFO: {{ template "secret.login" . | b64enc }}
    WORLD_DATABASE_INFO: {{ template "secret.world" . | b64enc }}
    CHARACTER_DATABASE_INFO: {{ template "secret.character" . | b64enc }}