apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}-world-service
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.world.service.type }}
  ports:
    - port: {{ .Values.world.service.port }}
      targetPort: 3724
      protocol: TCP
      name: "mangos-world"
  selector:
    app: {{ template "chart.name" . }}-world
    release: {{ .Release.Name }}
